# This is a basic workflow to help you get started with Actions

name: build Xamarin

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  SOLUTION_NAME: Estekhareh
  ANDROID_PROJECT_NAME: Estekhareh.Android
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Generate Xamarin Form Android APK
        # You may pin to the exact commit or the version.
        # uses: fahimshahrierrasel/Xamarin-Droid-Builder@3b0a1d8692d8ca70d3811f4f79743551da24cc60
        uses: fahimshahrierrasel/Xamarin-Droid-Builder@1.0.2
        with:
          # Solution Name or the root folder name.
          SOLUTION_NAME: Estekhareh
          # Android Project name or the folder name of the android project usually its end with .Android as postfix.
          ANDROID_PROJECT_NAME:  Estekhareh.Android
